// summaries.js

const summaries = {
    "Tinea Ringworm Candidiasis and other Fungal Infections": "Tinea, commonly known as ringworm, and candidiasis are fungal infections that affect the skin, nails, and mucous membranes. Tinea presents as a red, circular, and itchy rash, while candidiasis often causes white patches and itching in moist areas like the mouth and genitals. Treatment includes antifungal creams or oral medications, maintaining good hygiene, and keeping affected areas dry.",
    "Warts Molluscum and other Viral Infections": "Warts and molluscum are skin infections caused by viruses. Warts, caused by the human papillomavirus (HPV), appear as small, rough growths. Molluscum contagiosum, caused by a poxvirus, presents as small, firm, and painless bumps. Both conditions spread through direct contact and are typically self-limiting but can be treated with topical treatments or physical removal if needed.",
    "Basal Cell Carcinoma": "Basal cell carcinoma (BCC) is the most common type of skin cancer, arising from basal cells in the epidermis. BCC often appears as a pearly or waxy bump, a flat, flesh-colored lesion, or a sore that bleeds or scabs. While BCC grows slowly and rarely metastasizes, it can cause significant local damage. Treatment includes surgical excision, cryotherapy, or topical medications.",
    "Benign Keratosis-like Lesions": "Benign keratosis-like lesions, including seborrheic keratoses and actinic keratoses, are non-cancerous growths that appear as brown, black, or light-colored patches on the skin. Seborrheic keratoses have a waxy, wart-like appearance, while actinic keratoses are rough, scaly patches caused by sun exposure. Treatment options include cryotherapy, laser therapy, or topical treatments if removal is desired.",
    "Eczema": "Eczema, also known as atopic dermatitis, is a chronic skin condition characterized by inflamed, itchy, and red patches of skin. It commonly affects the face, neck, hands, and legs. Eczema can be triggered by various factors including allergens, stress, and irritants. Symptoms may include dry skin, severe itching, and oozing or crusting. Treatments include moisturizers, topical steroids, and antihistamines to manage symptoms.",
    "Melanocytic Nevi": "Melanocytic nevi, commonly known as moles, are benign growths of melanocytes, the pigment-producing cells of the skin. They can be flat or raised, and vary in color from pink to dark brown. While most moles are harmless, changes in size, shape, or color should be monitored for signs of melanoma. Regular skin checks and protection from sun exposure are recommended.",
    "Melanoma": "Melanoma is a serious form of skin cancer that develops from melanocytes. It can appear as a new mole or a change in an existing mole, often characterized by asymmetry, irregular borders, multiple colors, and increasing size. Early detection and treatment are crucial, as melanoma can spread rapidly. Treatment options include surgical removal, immunotherapy, and targeted therapy.",
    "Psoriasis pictures Lichen Planus and related diseases": "Psoriasis and lichen planus are chronic inflammatory skin conditions. Psoriasis causes red, scaly plaques commonly on the scalp, elbows, and knees, while lichen planus presents as purple, flat-topped bumps often on the wrists, lower back, and ankles. Both conditions are autoimmune in nature and can be managed with topical treatments, systemic medications, and lifestyle changes.",
    "Seborrheic Keratoses and other Benign Tumors": "Seborrheic keratoses are common, benign skin growths that appear as waxy, raised, and often pigmented lesions. They are typically found on the chest, back, and face. Other benign skin tumors include dermatofibromas, lipomas, and hemangiomas. While these growths are non-cancerous and usually asymptomatic, they can be removed for cosmetic reasons or if they become irritated.",
  };
  
  export default summaries;
  